// Generates public/js/icons.js from lucide-static (ISC license) — inline SVG
// path data, no runtime dependency. Re-run after changing ICONS; commit output.
import { readFileSync, writeFileSync } from 'node:fs';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');
const src = join(root, 'node_modules', 'lucide-static', 'icons');

// name-in-app → lucide file name
const ICONS = {
  play: 'play',
  stop: 'square',
  plus: 'plus',
  minus: 'minus',
  edit: 'pencil',
  trash: 'trash-2',
  copy: 'copy',
  clock: 'clock',
  timer: 'timer',
  calendar: 'calendar-days',
  search: 'search',
  stats: 'chart-column',
  folder: 'folder',
  folderOpen: 'folder-open',
  settings: 'settings',
  download: 'download',
  export: 'file-down',
  lock: 'lock',
  unlock: 'lock-open',
  eye: 'eye',
  star: 'star',
  pin: 'pin',
  chevronLeft: 'chevron-left',
  chevronRight: 'chevron-right',
  chevronDown: 'chevron-down',
  chevronUp: 'chevron-up',
  grip: 'grip-vertical',
  sparkles: 'sparkles',
  alert: 'triangle-alert',
  check: 'check',
  x: 'x',
  more: 'ellipsis',
  moreV: 'ellipsis-vertical',
  sortAZ: 'arrow-down-a-z',
  history: 'history',
  refresh: 'rotate-ccw',
  keyboard: 'keyboard',
  sun: 'sun',
  moon: 'moon',
  briefcase: 'briefcase',
  clipboard: 'clipboard-list',
  wand: 'wand-2',
  layout: 'layout-dashboard',
  archive: 'archive',
  archiveRestore: 'archive-restore',
};

const FALLBACKS = {
  'chart-column': ['bar-chart-3', 'bar-chart'],
  'triangle-alert': ['alert-triangle'],
  ellipsis: ['more-horizontal'],
  'ellipsis-vertical': ['more-vertical'],
  'wand-2': ['wand-sparkles', 'wand'],
  'lock-open': ['unlock', 'lock-keyhole-open'],
};

function loadSvg(name) {
  const candidates = [name, ...(FALLBACKS[name] || [])];
  for (const c of candidates) {
    try {
      return readFileSync(join(src, `${c}.svg`), 'utf8');
    } catch { /* try next */ }
  }
  throw new Error(`icon not found: ${name}`);
}

function innerMarkup(svg) {
  const m = svg.match(/<svg[^>]*>([\s\S]*)<\/svg>/);
  return m[1].trim().replace(/\n\s*/g, '');
}

const entries = Object.entries(ICONS).map(([key, file]) => {
  const inner = innerMarkup(loadSvg(file));
  return `  ${key}: ${JSON.stringify(inner)},`;
});

const out = `// GENERATED by scripts/build-icons.mjs from lucide-static (ISC license).
// Do not edit by hand — edit the ICONS map in the script and re-run.
const PATHS = {
${entries.join('\n')}
};

const React = window.React;

// Inline SVG icon. Default 19px (~20% larger than the emoji glyphs replaced).
export function Icon({ name, size = 19, className = '', label }) {
  const inner = PATHS[name];
  if (!inner) return null;
  return React.createElement('svg', {
    width: size,
    height: size,
    viewBox: '0 0 24 24',
    fill: 'none',
    stroke: 'currentColor',
    strokeWidth: 2,
    strokeLinecap: 'round',
    strokeLinejoin: 'round',
    className: 'icon ' + className,
    'aria-hidden': label ? undefined : true,
    'aria-label': label,
    role: label ? 'img' : undefined,
    dangerouslySetInnerHTML: { __html: inner },
  });
}

export const ICON_NAMES = Object.keys(PATHS);
`;

writeFileSync(join(root, 'public', 'js', 'icons.js'), out);
console.log(`wrote public/js/icons.js with ${Object.keys(ICONS).length} icons`);
